/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // docs 폴더 전체를 스캔
    },
  ],
}

module.exports = sidebars
